### ISSUE TITLE
Dto验证自定义信息的多语言

### ISSUE THREAD

**Issue by JunFWu** [52ABP/SPA.PhoneBook#1]
在Dto验证中，
[Required(ErrorMessage= "这个字段是必输的")]
实现自定义抛错，这个抛错Abp没有进行对多语言处理，请问在后台怎么进行多语言处理

**Comment by ltm0203** [comment]
你可以把ErrorMessage= "这个字段是必输的" 替换为常量，使用xml来进行替换为多语言。
